---
title: "Lab01 - Parte 4"
author: "Caio Oliveira"
date: "May 25, 2017"
output: 
 html_document:
  toc: true
  toc_float: true
---

<h1>Laboratório 1, Parte 4: Relatório final</h1>
<h2>Tema: Análise dos dados do IMDB</h2>
....

<h3>Tratamento inicial dos dados</h3>
```{r, include=FALSE}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  require(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```


```{r setup}
library(dplyr)
library(ggplot2)
library(gridExtra)


setwd("~/data-analysis-2/ad1/lab1")
data <- read.csv("series_from_imdb.csv")
series.selected.all.seasons <- data %>% filter(series_name %in% c("Arrow", "Sense8", "Daredevil", "Gotham", "Flash", "House of Cards"))

series.2.seasons <- series.selected.all.seasons %>% 
  filter(season < 3)


```


Quais são as top 10 melhores séries avaliadas? E quais são as piores? 



```{r}

a <- data.frame(data$series_name, data$UserVotes)
a <- na.omit(a)
colnames(a)[1] <- "name"
colnames(a)[2] <- "UserVotes"

series.per.vote <- a %>% 
  group_by(name) %>%
  summarise(votos = sum(UserVotes)) 
series.per.vote <- na.omit(series.per.vote) 

least.voted <- head(series.per.vote[order(series.per.vote$votos, decreasing = FALSE), ], n = 10)
most.voted <- head(series.per.vote[order(series.per.vote$votos, decreasing = TRUE), ], n = 10)


least.voted$name <- factor(least.voted$name, levels = least.voted$name[order(least.voted$votos)])
most.voted$name <- factor(most.voted$name, levels = most.voted$name[order(most.voted$votos)])
```


```{r}
least.voted
most.voted
```



```{r}
lv.plot <- ggplot(arrange(least.voted, votos), aes(name, votos, colour = name)) + geom_col(aes(fill=name)) + ylim(0, 150000)  + geom_smooth(method="lm") + coord_flip() + ggtitle("Séries menos votadas pelos usuários (UserVotes)")

mv.plot <- ggplot(arrange(most.voted, votos), aes(name, votos, colour = name)) + geom_col(aes(fill=name)) + ylim(0, 1500000)  + geom_smooth(method="lm") + coord_flip() + ggtitle("Séries mais votadas pelos usuários (UserVotes)")


lv.plot
mv.plot

```


Para outra variável que é o user rating
```{r}

a <- data.frame(data$series_name, data$UserRating)
a <- na.omit(a)
colnames(a)[1] <- "name"
colnames(a)[2] <- "UserRating"

series.per.vote <- a %>% 
  group_by(name) %>%
  summarise(votos = mean(UserRating)) 
series.per.vote <- na.omit(series.per.vote) 

least.voted <- head(series.per.vote[order(series.per.vote$votos, decreasing = FALSE), ], n = 10)
most.voted <- head(series.per.vote[order(series.per.vote$votos, decreasing = TRUE), ], n = 10)


least.voted$name <- factor(least.voted$name, levels = least.voted$name[order(least.voted$votos)])
most.voted$name <- factor(most.voted$name, levels = most.voted$name[order(most.voted$votos)])

```

```{r}
least.voted
most.voted
```


```{r}
lv.plot <- ggplot(arrange(least.voted, votos), aes(name, votos, colour = name)) + geom_col(aes(fill=name)) + ylim(0, 10)  + geom_smooth(method="lm") + coord_flip() + ggtitle("Séries menos votadas pelos usuários (UserVotes)")

mv.plot <- ggplot(arrange(most.voted, votos), aes(name, votos, colour = name)) + geom_col(aes(fill=name)) + ylim(0, 10)  + geom_smooth(method="lm") + coord_flip() + ggtitle("Séries mais votadas pelos usuários (UserVotes)")


lv.plot
mv.plot

```


Dado um conjunto finito de séries com segunda temporada, geralmente qual temporada tem melhores notas? A primeira ou a segunda?


```{r}

series.2 <-  data.frame(series.2.seasons$series_name,series.2.seasons$season,series.2.seasons$UserRating)
series.2 <- na.omit(series.2)
colnames(series.2)[1] <- "name"
colnames(series.2)[2] <- "season"
colnames(series.2)[3] <- "UserRating"


series.season.1 <- series.2 %>%
  group_by(name,season) %>%
  filter(season == 1) %>%
  summarise(media = mean(UserRating))

series.season.2 <- series.2 %>%
  group_by(name,season) %>%
  filter(season == 2) %>%
  summarise(media = mean(UserRating))

series.formated <- rbind(series.season.1,series.season.2)

#ggplot(ddf, aes(x=GRP, y=NUMS)) + geom_boxplot(outlier.shape=NA) + geom_jitter(position=position_jitter(width=.1, height=0))
```








