---
title: "Lab-03"
author: "Caio Oliveira"
date: "December 11, 2016"
output: html_document
---

<h3>Importando os dados de treino primeiro</h3>
```{r}
library(caret)

library(readr)
library(dplyr)
graduados <- read_csv("graduados_treino.csv", col_types = cols(ALU_NOVAMATRICULA = col_character())) %>%
  mutate(ALU_NOVAMATRICULA = as.factor(ALU_NOVAMATRICULA))
head(graduados)
```


```{r}

str(graduados)
summary(graduados)
View(graduados)
graduados <- graduados %>%
  arrange(ALU_NOVAMATRICULA)

```

```{r}

graduados.clean <- graduados %>%
  filter(!is.na(MAT_MEDIA_FINAL))

summary(graduados.clean)
View(graduados.clean)

graduados.cra <- graduados.clean %>%
  group_by(ALU_NOVAMATRICULA) %>%
  mutate(cra.contrib = MAT_MEDIA_FINAL*CREDITOS) %>%
  summarise(cra = sum(cra.contrib)/sum(CREDITOS))

head(graduados.cra)


```
```{r}

library(reshape2)

graduados.model.input <- graduados.clean %>%
  group_by(ALU_NOVAMATRICULA,DISCIPLINA)  %>%
  filter(MAT_MEDIA_FINAL == max(MAT_MEDIA_FINAL)) %>%
  ungroup() %>%
  select(ALU_NOVAMATRICULA,DISCIPLINA,MAT_MEDIA_FINAL) %>% 
  mutate(DISCIPLINA = as.factor(gsub(" ",".",DISCIPLINA))) %>%
  dcast(ALU_NOVAMATRICULA ~ DISCIPLINA, mean) %>%
  merge(graduados.cra)

head(graduados.model.input)
View(graduados.model.input)
```


<h3>Pegamos os dados de cada uma das disciplinas em variáveis</h3> 

```{r}
#primeiro periodo
CI <- graduados.model.input$Cálculo.Diferencial.e.Integral.I
AV <- graduados.model.input$Álgebra.Vetorial.e.Geometria.Analítica
IC <- graduados.model.input$Introdução.à.Computação  
LPI <- graduados.model.input$Laboratório.de.Programação.I
PI <- graduados.model.input$Programação.I
LPT <- graduados.model.input$Leitura.e.Produção.de.Textos
  
#segundo periodo

TG <- graduados.model.input$Teoria.dos.Grafos    
PII <- graduados.model.input$Programação.II  
LPII <- graduados.model.input$Laboratório.de.Programação.II
CII <- graduados.model.input$Cálculo.Diferencial.e.Integral.II  
FFC <- graduados.model.input$Fundamentos.de.Física.Clássica   
MD <- graduados.model.input$Matemática.Discreta 

  
```



<h3>Fazendo regressão Ridge para os dois períodos</h3>

```{r}
library(ISLR)
library(caret)
library(alr3)
options("na.action")



g<-graduados.model.input[complete.cases(graduados.model.input),]
split <- createDataPartition(y=g$cra, p = 0.9, list = FALSE)
train <- g[split,]
test <- g[-split,]
set.seed(825) # for reproducing these results
ridge <- train(cra ~ CI +  AV + IC + PI + LPI + LPT, data = g,
               method='ridge',
               lambda = 4,
               preProcess=c('scale', 'center'), na.action="na.exclude")

ridge

```






























